### ISSUE TITLE
Design corrections to "Connection details" screen

### ISSUE THREAD

**Issue by carlos8silva** [intersection-labs/connector-iOS#1]
Apply the following corrections to the "Connection details" screen:
- Button colour should be #FF2D55
- Move text in button 1 pixel up
- Font size of "No reminders set" label does not appear to be correct
- Spacing between separator and "No reminders set" label must be 40px
- Spacing between "No reminders set" label and "Add a reminder" button must be 30px

**Comment by mkramskoy** [comment]
Everything should be fixed in 0.1(9) build
